# Generated by Django 3.2.5 on 2023-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashin', '0002_auto_20230423_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='search_history',
        ),
        migrations.AlterField(
            model_name='movie',
            name='click_through_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='num_of_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='num_of_times_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='search',
            name='num_movies_liked',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
