# Generated by Django 3.2.5 on 2023-04-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashin', '0003_auto_20230423_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='review_num',
        ),
    ]
